<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('clientes')->insert([
            [
                'ruc_cedula' => '1792850193001',
                'nombre_comercial' => 'KYROVET LABORATORIES DE ECUADOR S.A.',
                'direccion' => 'REINA VICTORIA N25-33 Y AV. COL?N',
                'telefono' => '023826822\\0998396145',
                'email' => 'kyrovetecuador@gmail.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1712082179',
                'nombre_comercial' => 'SANTAMARIA HERRERIA CARLOS FRANCISCO',
                'direccion' => 'CHAUPICRUZ',
                'telefono' => '022428555\\0982816539',
                'email' => 's/n',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792116104001',
                'nombre_comercial' => 'ECOLAB ECUADOR CIA. LTDA.',
                'direccion' => 'LUXEMBURGO N 34-3 59 Y PORTUGAL EDF COSMOPOLITAN PARC OFC 414',
                'telefono' => '022472474\\0997189258',
                'email' => 'edwin.santillan@ecolab.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1793194894001',
                'nombre_comercial' => 'PROTEKTING PHYTOSANITARY ECUADOR S.A.S.',
                'direccion' => 'CALLE B Y CALLE C',
                'telefono' => '022428555',
                'email' => 'angela.gonzalez@protekting.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792599040001',
                'nombre_comercial' => 'SUMMIT AGRO SOUTH AMERICA SPA',
                'direccion' => 'AV. PAMPITE S/N Y PASAJE DARÍO DONOSO, EDIFICIO OFFICENTER, OFICINA 315',
                'telefono' => '025000134\\022261753',
                'email' => 'patricia.garcia@summit-agro.com;miguel.racines@summit-agro.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792522005001',
                'nombre_comercial' => 'PRECISAGRO S.A.',
                'direccion' => 'AV LAS MONJAS Y CARLOS JULIO AROSEMENA KILÓMETRO: 2.5 EDIFICIO: HAMBURGO',
                'telefono' => '022869363\\0983168051',
                'email' => 'kgatica@disagro.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792768934001',
                'nombre_comercial' => 'ECOFOSECUATORIANA S.A.',
                'direccion' => 'EUCALIPTOS OE423 Y EUGENIO ESPEJO',
                'telefono' => '022428555\\0999728004',
                'email' => 'ahurtado@attorneys.com.ec',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1791853873001',
                'nombre_comercial' => 'ARYSTA-LIFESCIENCE ECUADOR S.A.',
                'direccion' => 'AV. COLON 1468 Y AV. NUEVE DE OCTUBRE',
                'telefono' => '022239494\\0992917075',
                'email' => 'jsalazar@bposervices.ec',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792375975001',
                'nombre_comercial' => 'MIRAMONT COMERCIALIZADORA DE INSUMOS AGRICOLAS MCI S.A.',
                'direccion' => 'AV. MARCO AURELIO SUBIA S',
                'telefono' => '022428555\\0989490497',
                'email' => 'contabilidad@miramont.com.ec',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0992233222001',
                'nombre_comercial' => 'AGRITOP S.A.',
                'direccion' => 'VIA A SAMBORONDON KILÓMETRO TRES JUNTO A LA SUBESTACION DE EMELGUR',
                'telefono' => '042837819\\042837750\\0986206067\\0986398477',
                'email' => 'aguaraca@aifasa.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0992460598001',
                'nombre_comercial' => 'ADAMA ANDINA B.V',
                'direccion' => 'PUERTO SANTA ANA MZ 1 SL 8 EDIF. POINT',
                'telefono' => '042597919\\042597919',
                'email' => 'andrea.espinoza@adama.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792800609001',
                'nombre_comercial' => 'PHIBRO ANIMAL HEALTH CORPORATION',
                'direccion' => 'CATALINA ALDAZ N34-155 Y ELOY ALFARO',
                'telefono' => '022562680\\0999030454',
                'email' => 'roberto.acosta@pahc.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792136466001',
                'nombre_comercial' => 'QUATROAGRO ECUADOR S.A.',
                'direccion' => 'AV. SIENNA 318 Y CALLE A. EDIFICIO MEDEX OFICINA 109 PB. CUMBAYÁ',
                'telefono' => '022040087',
                'email' => 'gclopez@foragro.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1793192607001',
                'nombre_comercial' => 'REDBARNGROUP ECUADOR C.L.',
                'direccion' => 'CARLOS BRITO S/N Y UYUMBICHO',
                'telefono' => '022999999\\0958814341',
                'email' => 'carolina.morejon@redbarngroup.com.ec',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0992940425001',
                'nombre_comercial' => 'INDUSTRIAL BIOAGRICOLA DEL LITORAL LITOBIO C.A.',
                'direccion' => 'AVENIDA TERCERA 704 Y ENTRE FICUS Y GUAYACANES',
                'telefono' => '042287093\\0997509920',
                'email' => 'fbruckmann@cluzon.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1793128173001',
                'nombre_comercial' => 'RIMAC ECUADOR, S.A.S.',
                'direccion' => 'AV.12 DE OCTUBRE N24-774 Y AV. CORUÑA',
                'telefono' => '022567676',
                'email' => 'Otorre@rimacsa.co.cr',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792986796001',
                'nombre_comercial' => 'PARAMO ZERO PARAMOZERO CIA.LTDA.',
                'direccion' => 'FRANCISCO MARCOS N57-200 Y LEONARDO MURIALDO',
                'telefono' => '045008000\\0992500702',
                'email' => 'canne.ventas@gmail.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792325544001',
                'nombre_comercial' => 'NUTRIENTES E INSUMOS PARA ANIMALES NUTRINA CIA. LTDA.',
                'direccion' => 'SANTA LUCIA E8-48 Y DANIEL COMBONI',
                'telefono' => '023500331',
                'email' => 'rtobar@nutrinacorp.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1792379504001',
                'nombre_comercial' => 'AXALTA COATING SYSTEMS ECUADOR S.A.',
                'direccion' => 'PASAJE EL JARDIN N35C E10-05 Y AV. 6 DE DICIEMBRE',
                'telefono' => '023325703\\023325669',
                'email' => 'alvaro.barrionuevo@contractors.axaltacs.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1790971678001',
                'nombre_comercial' => 'AGROQUIM C. LTDA.',
                'direccion' => 'AV. SAN FRANCISCO N42-14 Y MARIANO ECHEVERRÍA',
                'telefono' => '022251066\\0997121947',
                'email' => 'f.chavez@agroquim.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0991369864001',
                'nombre_comercial' => 'TRANSCONTAINER S.A.',
                'direccion' => '6TA AVENIDA 710 Y CALLE QUINTA - CALLE SEXTA',
                'telefono' => '022428555',
                'email' => 's/n',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0991098127001',
                'nombre_comercial' => 'IMPORTADORA INDUSTRIAL AGRICOLA DEL MONTE SOCIEDAD ANONIMA INMONTE',
                'direccion' => 'KM 5 Y MEDIO SOLAR 2',
                'telefono' => '043700260',
                'email' => 'jmolina@delmonte.com.ec',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '0992734558001',
                'nombre_comercial' => 'FMC LATINOAMERICA S.A.',
                'direccion' => 'AV. FRANCISCO DE ORELLANA EDIFICIO WORLD TRADE CENTER TORRE A, PISO 11 OFICINA 1103',
                'telefono' => '043902886\\043902089\\0993195820',
                'email' => 'yelissabeth.guzman@fmc.com',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ruc_cedula' => '1791870891001',
                'nombre_comercial' => 'ALBAUGH ECUADOR S.A.',
                'direccion' => 'AV JUSTINO CORNEJO SOLAR1 SATIAGO CASTILLO EDIFICIO KENNEDY BUSINESS',
                'telefono' => '046008065\\0991737550',
                'email' => 'epulido@albaugh.com.mx',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
