<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuariosSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'nombre' => 'RICARDO JOAQUIN',
                'apellido' => 'BATALLAS MINDA',
                'correo' => 'ricardo.batallas@cripada.com',
                'telefono' => '0963064043',
                'password' => Hash::make('Desko2904'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg', // Puedes poner el nombre de la foto por defecto
                'idrol' => 1, // Asegúrate que este rol exista
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JORGE ISRAEL',
                'apellido' => 'PANAMÁ ZUMÁRRAGA ',
                'correo' => 'israel.panama@cripada.com',
                'telefono' => '0987882942',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg', // Puedes poner el nombre de la foto por defecto
                'idrol' => 1, // Asegúrate que este rol exista
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'GABRIELA PAOLA',
                'apellido' => 'TORRES BURGOS',
                'correo' => 'gabytorres1787@hotmail.com',
                'telefono' => '0989272091',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'GELKIN DENISSE',
                'apellido' => 'PONGUILLO ESCOBAR',
                'correo' => 'gelkin.ponguillo@cripada.com',
                'telefono' => '0988556831',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'MAURICIO FERNANDO',
                'apellido' => 'SANCHEZ BRIONES',
                'correo' => 'mauricio.sanchez@cripada.com',
                'telefono' => '0992017394',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JEFFERSON ALEJANDRO',
                'apellido' => 'APOLO CHÁVEZ',
                'correo' => 'jeffersonapolo25@gmail.com',
                'telefono' => '0978978075',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'MIRELLY EMPERATRIZ',
                'apellido' => 'LEON FAJARDO',
                'correo' => 'mirellileon64@gmail.com',
                'telefono' => '0980828790',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'KEVIN ROBERTO',
                'apellido' => 'ROSERO CHOLOTA',
                'correo' => 'Kroserocholota@gmail.com',
                'telefono' => '0986313940',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'ANDY LEONARDO',
                'apellido' => 'BAIDAL SANTO',
                'correo' => 'leo199606@outlook.com',
                'telefono' => '0985432731',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JEFFERSON VALENTIN',
                'apellido' => 'ECHEVERRIA SANCHEZ',
                'correo' => 'jeffersonecheverria31@gmail.com',
                'telefono' => '0995097238',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'OSCAR ALEJANDRO',
                'apellido' => 'ZAMBRANO CARRIEL',
                'correo' => 'a.zambrano86carriel@gmail.com',
                'telefono' => '978972000',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'CHRISTIAN PAUL',
                'apellido' => 'PICHUCHO TARAPUEZ',
                'correo' => 'cristian.pichu@hotmail.com',
                'telefono' => '0984926251',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JUAN JOSÉ',
                'apellido' => 'SIMBAÑA VALVERDE',
                'correo' => 'juanjosesv95@outlook.com',
                'telefono' => '0983249349',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'SALOMON DAVID',
                'apellido' => 'GAIBOR NOBOA',
                'correo' => 'dgaibornoboa@hotmail.com',
                'telefono' => '0984347112',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JASON ANÍBAL',
                'apellido' => 'CUASAPAZ LOVATO',
                'correo' => 'Jason96-1@hotmail.com',
                'telefono' => '0980219697',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'JORGE LUIS',
                'apellido' => 'OÑATE PEÑAFIEL',
                'correo' => 'jorgeluis-op19@hotmail.es',
                'telefono' => '0980407482',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'GABRIELA LIZETH',
                'apellido' => 'OYOLA AGUILAR',
                'correo' => 'gabriela.oyola@outlook.com',
                'telefono' => '0999960157',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'ORLEY VINICIO',
                'apellido' => 'PÁRRAGA MUÑOZ',
                'correo' => 'Orley.parraga1987@gmail.com',
                'telefono' => '0991164568',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'MARÍA VERÓNICA',
                'apellido' => 'MORALES FLORES',
                'correo' => 'veritto.morales@gmail.com',
                'telefono' => '0985113033',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'DAYANNA LIZETH',
                'apellido' => 'ALEMAN ORTEGA',
                'correo' => 'lis_d@hotmail.es',
                'telefono' => '0982473342',
                'password' => Hash::make('Pass1234'),
                'estado' => true,
                'foto' => 'fotos_usuarios/default.jpg',
                'idrol' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
