name: Sharedhosting Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Preparar Entorno Swagger
        run: php artisan l5-swagger:generate

